#!/bin/bash

function createLender() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/lender.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/lender.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-lender --tls.certfiles "${PWD}/organizations/fabric-ca/lender/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-lender.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-lender.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-lender.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-lender.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/lender.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy lender's CA cert to lender's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/lender.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/lender/ca-cert.pem" "${PWD}/organizations/peerOrganizations/lender.example.com/msp/tlscacerts/ca.crt"

  # Copy lender's CA cert to lender's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/lender.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/lender/ca-cert.pem" "${PWD}/organizations/peerOrganizations/lender.example.com/tlsca/tlsca.lender.example.com-cert.pem"

  # Copy lender's CA cert to lender's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/lender.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/lender/ca-cert.pem" "${PWD}/organizations/peerOrganizations/lender.example.com/ca/ca.lender.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-lender --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/lender/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-lender --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/lender/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-lender --id.name lenderadmin --id.secret lenderadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/lender/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-lender -M "${PWD}/organizations/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/msp" --csr.hosts peer0.lender.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/lender/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/lender.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-lender -M "${PWD}/organizations/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls" --enrollment.profile tls --csr.hosts peer0.lender.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/lender/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/lender.example.com/peers/peer0.lender.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-lender -M "${PWD}/organizations/peerOrganizations/lender.example.com/users/User1@lender.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/lender/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/lender.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/lender.example.com/users/User1@lender.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://lenderadmin:lenderadminpw@localhost:7054 --caname ca-lender -M "${PWD}/organizations/peerOrganizations/lender.example.com/users/Admin@lender.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/lender/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/lender.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/lender.example.com/users/Admin@lender.example.com/msp/config.yaml"
}

function createBorrower() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/borrower.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/borrower.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-borrower --tls.certfiles "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-borrower.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-borrower.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-borrower.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-borrower.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/borrower.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy borrower's CA cert to borrower's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/borrower.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem" "${PWD}/organizations/peerOrganizations/borrower.example.com/msp/tlscacerts/ca.crt"

  # Copy borrower's CA cert to borrower's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/borrower.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem" "${PWD}/organizations/peerOrganizations/borrower.example.com/tlsca/tlsca.borrower.example.com-cert.pem"

  # Copy borrower's CA cert to borrower's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/borrower.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem" "${PWD}/organizations/peerOrganizations/borrower.example.com/ca/ca.borrower.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-borrower --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-borrower --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-borrower --id.name borroweradmin --id.secret borroweradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-borrower -M "${PWD}/organizations/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/msp" --csr.hosts peer0.borrower.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/borrower.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-borrower -M "${PWD}/organizations/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/tls" --enrollment.profile tls --csr.hosts peer0.borrower.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/borrower.example.com/peers/peer0.borrower.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-borrower -M "${PWD}/organizations/peerOrganizations/borrower.example.com/users/User1@borrower.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/borrower.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/borrower.example.com/users/User1@borrower.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://borroweradmin:borroweradminpw@localhost:8054 --caname ca-borrower -M "${PWD}/organizations/peerOrganizations/borrower.example.com/users/Admin@borrower.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/borrower/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/borrower.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/borrower.example.com/users/Admin@borrower.example.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp" --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls" --enrollment.profile tls --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
